### ISSUE TITLE
Bad work

### ISSUE THREAD

**Issue by Brucestraw** [IVY-LVLM/Counterfactual-Inception#1]
1. Overreliance on GPT-4V for Hallucination Mitigation
The strategy of using GPT-4V to reduce hallucinations heavily relies on this specific model, which makes the approach impractical for those without access to GPT-4V. Without it, the method's effectiveness is significantly diminished, rendering it nearly useless work.

2. Questionable Validity of Cherry-Picked Results
Figures 1, 2, and 5 appears to be a clear case of cherry-picking, which severely undermines the integrity of the study. Such selective presentation is misleading and does not provide a fair representation of the overall performance.

3. Insignificant Performance Gains
The reported improvements of 3-4% are negligible, especially in the vision-language domain where at least a 10% increase is necessary to be considered meaningful. These marginal gains, even with the help of GPT-4V, fail to justify the approach, suggesting that the method offers little real value.

4. Neglecting Essential Instruction Tuning
The failure to include instruction tuning is a major oversight. Instruction tuning is crucial for training robust models, and ignoring it weakens the entire methodology. Despite using it, you will still use GPT-4V, also useless works.

5. Questionable Pursuit of Reducing Hallucinations
Attempting to reduce hallucinations, a natural phenomenon of generative models, is fundamentally misguided. The entire premise of this research is questionable since hallucinations are intrinsic to these models. The effort to eliminate them may be futile, casting doubt on its validity.

**Comment by jhkim0911** [comment]
Thank you for your critical views and reviews. But, at the same time, we believe that this is not a trivial and useless work. There are so many researchers who engage in mitigating this hallucination effects in LMMs. We respect your personal perspective, but cannot agree saying this research direction is useless.  

This work is experimentally conducted with the initial idea of what-if scenario and it is "work in progress". 

Actually, we are improving our method via self-generated counterfactual keywords and will release the results and code soon. Please see how this work will be finished at the end.

Meanwhile, we recommend our new work!
https://ivy-lvlm.github.io/CODE/

**Comment by jhkim0911** [comment]
Thank you for taking time to review.

Can we discuss more?
arkimjh@kaist.ac.kr
